spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mariadb://localhost:3306/selfclocking
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create